import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { combineEvents, getPastEvents, getUpcomingEvents, getWhitePaper, getWhitePaperLink, getWhitePapers, getEvent } from '../api-lib/apiOps'

export async function getServerSideProps(context) {
  // const events = await fetch("https://nvsi-strapi-backend.herokuapp.com/api/events");
  // const even = await events.json();
  // console.log("TESTING");
  // console.log(even);
  const events = await getPastEvents();
  //const json = await events.json();
  console.log("PAST EVENTS", events);

  const upEvents = await getUpcomingEvents();
  // const json2 = await upEvents.json();
  console.log(upEvents);
  let whitePapers = await getWhitePapers();
  // console.log("WHITEPAPERS", await getWhitePapers());
  console.log(getWhitePaperLink(whitePapers, 1));
  // console.log(await events.json());

  //Testing for getting events

  let allEvents = combineEvents(events,upEvents);
  const tag = "test"
  console.log(getEvent(allEvents,tag));

  return {
    props: {

    }
  }
}

export async function getServerSideProps(context) {
  const {query} = context
  if (JSON.stringify(query) === '{}') {
    var events = await fetch(`http://localhost:1337/api/events?sort[0]=Date&sort[1]=StartTime`);
  } else {
    var events = await fetch(`http://localhost:1337/api/events?filters[tag][$containsi]=${query.tag}&sort[0]=Date&sort[1]=StartTime`);
  }
  const eventsRes = await events.json();
  console.log(eventsRes.data)
  return {
    props: {
      data : eventsRes
    }
  }
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
