import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.header}>
          <div className={styles.title}>
            <h1>WHITE PAPERS</h1>
          </div>
          <div id={styles.description}><h3>Featured Papers</h3></div>
        </div>
    </div>


    <div className={styles.main2}>
       <div className={styles.coming_soon}>COMING SOON...</div>
    </div>



    {/*TASKS:
      - fix font
      */}


      {/* FOOTER DONT TOUCH */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
